### ISSUE TITLE
foss2020a / OpenMPI / UCX issues

### ISSUE THREAD

**Issue by mand35** [hpc-unibe-ch/ubelix-easyconfigs#15]
While building the EasyBuild foss/2020a toolchain including:
- OpenMPI/4.0.3-GCC-9.3.0 and
- UCX/1.8.0-GCCcore-9.3.0
we get the following warnings when running standard MPI test cases:
```
-----------------------------------------------------------
WARNING: There was an error initializing an OpenFabrics device.
  Local host:   anode229
  Local device: mlx4_0
-----------------------------------------------------------
```
- The previous version with foss/2019b does not show that Warning/error.
- But the newer version shows significantly lower latencies in OSU test (good)
- OpenMPI configure is using UCX: --with-ucx=/software.el7/software/UCX/1.8.0-GCCcore-9.3.0
- Already tested reinstalling the OpenMPI with slurm and pmi support, no change
- Already tested reinstalling UCX (without modifications), no change

**Comment by mand35** [comment]
export OMPI_MCA_btl_openib_allow_ib=1
prevents the error message, but is it the proper solution?

**Comment by mrolli** [comment]
By default, for Open MPI 4.0 and later, infiniband ports on a device
are not used by default. The intent is to use UCX for these devices.
You can override this policy by setting the btl_openib_allow_ib MCA parameter
to true.

**Comment by mrolli** [comment]
As of OMPI-5.0 ucx will be the default and openib will get abandoned.

Sources:
https://github.com/open-mpi/ompi/issues/7555
https://github.com/open-mpi/ompi/issues/6300

**Comment by mand35** [comment]
Unfortunately in the foss/2020a installation the upstream OpenMPI were used, where 
`configopts = '--with-slurm --with-pmi --with-ucx'` is missing. 
The OpenMPI easyconfig was updated in the ubelix repo and installed. This fixed the Warning message.
