### ISSUE TITLE
MPI issues with INTEL

### ISSUE THREAD

**Issue by mand35** [hpc-unibe-ch/ubelix-easyconfigs#16]
any application build with mpi** (mpicc) of intel/2020a crashes with runtime errors:

$ module list

Currently Loaded Modules:
  1) CustomRepo/user                  4) binutils/.2.34-GCCcore-9.3.0 (H)   7) numactl/2.0.13-GCCcore-9.3.0         10) iimpi/2020a
  2) EasyBuild/4.2.1                  5) iccifort/2020.1.217                8) UCX/1.8.0-GCCcore-9.3.0              11) imkl/2020.1.217-iimpi-2020a
  3) zlib/.1.2.11-GCCcore-9.3.0 (H)   6) GCCcore/9.3.0                      9) impi/2019.7.217-iccifort-2020.1.217  12) intel/2020a

  Where:
   H:  Hidden Module

$ mpiicc -fopenmp ~/src/xthi.c -o xthi_intel.exe
$ srun -n2 xthi_intel.exe

slurmstepd: error: mpi/pmi2: value not properly terminated in client request
slurmstepd: error: mpi/pmi2: request not begin with 'cmd='
slurmstepd: error: mpi/pmi2: full request is: 000000000000000000000000000000000000000000000000
slurmstepd: error: mpi/pmi2: invalid client request
Abort(2664079) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init: Other MPI error, error stack:
MPIR_Init_thread(136)........:
MPID_Init(904)...............:
MPIDI_OFI_mpi_init_hook(1421):
MPIDU_bc_table_create(335)...:

**Comment by mand35** [comment]
```
 :) 11:56:05 submit03 ~/work/201202_stressTests/mpi_test $
salloc  -t 50
salloc: Pending job allocation 38629338
salloc: job 38629338 queued and waiting for resources
salloc: job 38629338 has been allocated resources
salloc: Granted job allocation 38629338
salloc: Waiting for resource configuration
salloc: Nodes anode232 are ready for job
  :) 11:56:15 submit03 ~/work/201202_stressTests/mpi_test $
module load intel
  :) 11:56:20 submit03 ~/work/201202_stressTests/mpi_test $
mpicc -fopenmp ~/src/xthi.c
  :) 11:56:23 submit03 ~/work/201202_stressTests/mpi_test $
srun ./a.out
slurmstepd: error: mpi/pmi2: value not properly terminated in client request
slurmstepd: error: mpi/pmi2: request not begin with 'cmd='
slurmstepd: error: mpi/pmi2: full request is: 000000000000000000000000000000000000000000000000

slurmstepd: error: mpi/pmi2: invalid client request
Abort(2664079) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init: Other MPI error, error stack:
MPIR_Init_thread(136)........:
MPID_Init(904)...............:
MPIDI_OFI_mpi_init_hook(1421):
MPIDU_bc_table_create(335)...:
srun: error: anode232: task 0: Exited with exit code 143
  :) 11:56:28 submit03 ~/work/201202_stressTests/mpi_test $
export FI_PROVIDER=verbs
  :) 12:02:52 submit03 ~/work/201202_stressTests/mpi_test $
srun ./a.out
WARNING: release_mt library was used but no multi-ep feature was enabled. Please use release library instead.
Hello from rank 0, thread 0, on anode232. (core affinity = 10)
  :) 12:02:54 submit03 ~/work/201202_stressTests/mpi_test $
```

**Comment by mand35** [comment]
Instead of using the upstream easyconfig as is, we need to enable 'I_MPI_PMI_LIBRARY': 'libpmi2.so'. Furthermore, the new version removed the ".../intel64/lib/release-mt" from LD_LIBRARY_PATH, thus no Warning anymore.

**Comment by bphusted** [comment]
I have the same problem with intel-2020b, but I do not fully understand the answer. Where do in enable  'I_MPI_PMI_LIBRARY': 'libpmi2.so'. ? Should I do an export in my slurm script or in the module files when loading intel mpi? Please clarify.

**Comment by bphusted** [comment]
I got it to work by setting adding a line in the impi lua file.
setenv("I_MPI_PMI_LIBRARY","/home/path/slurm-20.11.7/contribs/pmi/.libs/libpmi.so")
That seemed to solve the problem, but is it better to use the libpmi2.so file?

**Comment by mand35** [comment]
I am sorry, did not see the comments from @bphusted. My solution was to add the following to the impi easyconfig, e.g. https://github.com/hpc-unibe-ch/ubelix-easyconfigs/blob/master/i/impi/impi-2019.9.304-iccifort-2020.4.304.eb 

```
modextravars = {
    # to enable SLURM integration with srun (site-specific)
    'I_MPI_PMI_LIBRARY': 'libpmi2.so',
}
```
When building with easybuild the related impi lua file will have the mentioned `setenv("I_MPI_PMI_LIBRARY","libpmi2.so")`.
